import React from 'react';
import { Lead } from '../../types';
import { CheckCircle2, Circle, Clock, User, Phone, FileText, CreditCard, Briefcase } from 'lucide-react';

interface LeadTimelineProps {
  lead: Lead;
  onClose?: () => void;
}

export const LeadTimeline: React.FC<LeadTimelineProps> = ({ lead, onClose }) => {
  const default9Steps = [
    { title: '1. Lead generated by Team A', done: true, date: lead.createdDate, author: lead.assignedTeamA || 'Team A' },
    { title: '2. Forwarded to Team B', done: !!lead.forwardedToTeamB, date: lead.forwardedDate || lead.createdDate, author: lead.assignedTeamA || 'Team A' },
    { title: '3. Call completed', done: (lead.calls && lead.calls.length > 0) || (lead.callRecords && lead.callRecords.length > 0), date: lead.calls?.[0]?.date, author: lead.assignedTeamB || 'Team B' },
    { title: '4. Follow-up completed', done: lead.followUps?.some(f => f.status === 'Completed') || lead.status === 'Selected' || lead.status === 'Completed', date: lead.followUpDate, author: lead.assignedTeamB || 'Team B' },
    { title: '5. Client selected', done: ['Selected', 'In Execution', 'Converted', 'Completed'].includes(lead.status), date: lead.requirements?.date || lead.createdDate, author: lead.assignedTeamB || 'Team B' },
    { title: '6. Requirements collected', done: !!lead.requirements, date: lead.requirements?.date, author: lead.requirements?.recordedBy || lead.assignedTeamB || 'Team B' },
    { title: '7. Payment confirmed', done: !!lead.payment, date: lead.payment?.paymentDate, author: lead.payment?.recordedBy || lead.assignedTeamB || 'Team B' },
    { title: '8. Project assigned to Team C', done: ['In Execution', 'Completed', 'Converted'].includes(lead.status) || !!lead.assignedTeamC, date: lead.requirements?.date, author: 'Admin' },
    { title: '9. Project completed', done: lead.status === 'Completed', date: lead.status === 'Completed' ? new Date().toISOString() : undefined, author: lead.assignedTeamC || 'Team C' },
  ];

  const content = (
    <div className="space-y-6 font-sans">
      
      {/* Overview Info Card */}
      <div className="p-4 rounded-2xl bg-[#1F1117] border border-[#3A1F2B] space-y-2 text-xs">
        <div className="flex justify-between font-mono">
          <span className="text-[#C9B8BE]">Lead ID & Name:</span>
          <span className="text-[#FFF9F2] font-bold">{lead.id} — {lead.name} ({lead.company})</span>
        </div>
        <div className="flex justify-between font-mono">
          <span className="text-[#C9B8BE]">Contact & Area:</span>
          <span className="text-[#FFF9F2] font-medium">{lead.phone} • {lead.location || lead.area}</span>
        </div>
        {lead.requirements && (
          <div className="p-2.5 rounded-xl bg-[#2B1720] border border-[#D4A017]/30 space-y-1 mt-2">
            <div className="text-[11px] font-mono text-[#D4A017] font-bold uppercase flex items-center gap-1">
              <FileText className="w-3.5 h-3.5" /> Client Requirements: {lead.requirements.category}
            </div>
            <div className="text-xs text-[#FFF9F2]">{lead.requirements.detailedRequirement}</div>
          </div>
        )}
        {lead.payment && (
          <div className="p-2.5 rounded-xl bg-[#2B1720] border border-[#E8C766]/30 flex items-center justify-between mt-2 font-mono text-xs">
            <span className="text-[#E8C766] font-bold flex items-center gap-1">
              <CreditCard className="w-3.5 h-3.5" /> Payment Status: {lead.payment.status}
            </span>
            <span className="text-[#FFF9F2] font-bold">₹{lead.payment.amount.toLocaleString('en-IN')} (Ref: {lead.payment.transactionId})</span>
          </div>
        )}
      </div>

      {/* 9-Step Lead Journey Progress Overview Bar */}
      <div className="p-4 rounded-2xl bg-[#2B1720] border border-[#3A1F2B] space-y-3">
        <div className="text-xs font-mono font-bold text-[#FFF9F2] uppercase tracking-wider flex items-center justify-between">
          <span>9-Step Client Journey Workflow</span>
          <span className="text-[#D4A017]">
            {default9Steps.filter(s => s.done).length} / 9 Stages Completed
          </span>
        </div>
        
        <div className="grid grid-cols-3 sm:grid-cols-9 gap-1.5 pt-1">
          {default9Steps.map((step, idx) => (
            <div
              key={idx}
              className={`p-2 rounded-xl text-[10px] font-mono text-center border space-y-1 transition-all ${
                step.done
                  ? 'bg-[#D4A017]/15 border-[#D4A017]/50 text-[#D4A017]'
                  : 'bg-[#1F1117] border-[#3A1F2B] text-[#C9B8BE]'
              }`}
              title={step.title}
            >
              <div className="font-bold">{idx + 1}</div>
              <div className="truncate">{step.title.split('. ')[1]}</div>
            </div>
          ))}
        </div>
      </div>

      {/* Journey Timeline Activity Stream */}
      <div className="relative pl-6 space-y-6 before:absolute before:left-2.5 before:top-2 before:bottom-2 before:w-0.5 before:bg-gradient-to-b before:from-[#D4A017] before:via-[#E8C766] before:to-[#5A1833]">
        {lead.journey && lead.journey.length > 0 ? (
          lead.journey.map((step, idx) => (
            <div key={idx} className="relative space-y-1 group">
              <div className="absolute -left-[27px] top-1.5 w-4 h-4 rounded-full bg-[#1F1117] border-2 border-[#D4A017] flex items-center justify-center shadow-[0_0_10px_rgba(212,160,23,0.5)]">
                <div className="w-1.5 h-1.5 rounded-full bg-[#D4A017]" />
              </div>

              <div className="flex items-center justify-between text-xs font-mono">
                <span className="font-bold text-[#D4A017] uppercase tracking-wider">{step.stage}</span>
                <span className="text-[#C9B8BE]">
                  {step.timestamp ? new Date(step.timestamp).toLocaleDateString([], { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' }) : ''}
                </span>
              </div>

              <div className="p-3.5 rounded-xl bg-[#1F1117] border border-[#3A1F2B] space-y-1">
                <p className="text-xs text-[#FFF9F2] font-medium">{step.details}</p>
                <div className="text-[10px] text-[#C9B8BE] font-mono flex items-center gap-1">
                  <User className="w-3 h-3 text-[#D4A017]" /> By: {step.author}
                </div>
              </div>
            </div>
          ))
        ) : (
          default9Steps.filter(s => s.done).map((step, idx) => (
            <div key={idx} className="relative space-y-1 group">
              <div className="absolute -left-[27px] top-1.5 w-4 h-4 rounded-full bg-[#1F1117] border-2 border-[#E8C766] flex items-center justify-center shadow-[0_0_10px_rgba(232,199,102,0.5)]">
                <div className="w-1.5 h-1.5 rounded-full bg-[#E8C766]" />
              </div>
              <div className="text-xs font-mono font-bold text-[#FFF9F2]">{step.title}</div>
              <div className="text-xs text-[#C9B8BE] font-mono">Completed by {step.author}</div>
            </div>
          ))
        )}
      </div>
    </div>
  );

  if (onClose) {
    return (
      <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-md">
        <div className="w-full max-w-2xl max-h-[85vh] overflow-y-auto rounded-2xl bg-[#2B1720] border border-[#3A1F2B] p-6 space-y-4 shadow-2xl animate-in zoom-in-95">
          <div className="flex items-center justify-between border-b border-[#3A1F2B] pb-3">
            <h3 className="text-base font-bold text-[#FFF9F2] font-mono flex items-center gap-2">
              <span>Lead Journey Timeline ({lead.id})</span>
            </h3>
            <button onClick={onClose} className="text-[#C9B8BE] hover:text-[#FFF9F2] font-bold">✕</button>
          </div>
          {content}
        </div>
      </div>
    );
  }

  return content;
};
